name: giao_dien_trang_home
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  # carousel_slider: 4.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_countdown_timer: ^4.1.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.5.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  http: 1.5.0
  fl_chart: ^0.65.0
  url_launcher: ^6.2.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

